language: haskell
before_install:
    - openssl aes-256-cbc -K $encrypted_20ea0b3ef7d9_key -iv $encrypted_20ea0b3ef7d9_iv -in s3cfg.enc -out s3cfg -d
install:
    - sudo apt-get install s3cmd python-imaging
    - cabal install
    - cd site-content
script: travisblog build
after_script:
    - dist/build/travisblog/travisblog deploy
    - cd ..